# Generated by Django 3.0.2 on 2020-02-02 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer_uuid',
            field=models.UUIDField(default=uuid.UUID('a27d6b81-d0d9-4f70-a7db-5236298f08ed'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_uuid',
            field=models.UUIDField(default=uuid.UUID('e3dc5753-a785-46b1-8bb9-c722fe2c3e36'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historybuyer',
            name='history_uuid',
            field=models.UUIDField(default=uuid.UUID('9229237c-5829-42a3-8048-c94355f5980d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
