# Generated by Django 3.0.2 on 2020-02-02 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20200202_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer_uuid',
            field=models.UUIDField(default=uuid.UUID('7b7163f3-8e6d-4794-96d6-3edeca89a7cc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_uuid',
            field=models.UUIDField(default=uuid.UUID('56fa83b6-69a3-4173-aad9-2950ba16360c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historybuyer',
            name='history_uuid',
            field=models.UUIDField(default=uuid.UUID('ebf822b9-2dc1-497e-a603-fa06825e9913'), editable=False, primary_key=True, serialize=False),
        ),
    ]
