# Generated by Django 3.0.2 on 2020-02-02 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_auto_20200202_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer_uuid',
            field=models.UUIDField(default=uuid.UUID('96feb4bf-9974-4855-9493-dfefbb9dcd20'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_uuid',
            field=models.UUIDField(default=uuid.UUID('17faf18d-7956-4549-874f-f07ce644bbc9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historybuyer',
            name='history_uuid',
            field=models.UUIDField(default=uuid.UUID('1b0860db-c2e2-45d8-b791-15661b2b52fa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
