# Generated by Django 3.0.2 on 2020-02-03 05:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_auto_20200202_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer_uuid',
            field=models.UUIDField(default=uuid.UUID('d80bcee2-0edd-4819-8d5f-55ffc165f427'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_uuid',
            field=models.UUIDField(default=uuid.UUID('18c4c6d0-7200-4a10-82c9-22f3599f0763'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historybuyer',
            name='history_uuid',
            field=models.UUIDField(default=uuid.UUID('b1e12c09-9353-4edc-927a-6576967f5534'), editable=False, primary_key=True, serialize=False),
        ),
    ]
