# Generated by Django 3.0.2 on 2020-02-03 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_auto_20200203_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_uuid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_uuid',
        ),
        migrations.RemoveField(
            model_name='historybuyer',
            name='history_uuid',
        ),
        migrations.AddField(
            model_name='buyer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e51d1d0-bda5-4b0d-b5a7-2bb78991b620'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b272b07d-cb28-47fa-8b1e-4d22e73c4a0c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='historybuyer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('505e0910-076a-4d8c-8d85-618165dc0c76'), editable=False, primary_key=True, serialize=False),
        ),
    ]
