# Generated by Django 3.0.2 on 2020-02-03 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_auto_20200203_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1731385e-6a0c-43c4-98a5-c30787793c49'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c36ebea0-8193-4d85-b9e5-d6ff8ed9485b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historybuyer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9cff25b1-1f15-4419-a222-2a73e9280daa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
