# Generated by Django 3.0.2 on 2020-02-03 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_auto_20200203_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cca4f5b6-e78d-42df-b965-a2d5ff54ce39'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4839d7ff-7f90-4259-9daa-26e4a6e20086'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='historybuyer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='historybuyer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d9f2f111-e04f-4b01-a639-5a7a6ed39e2e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
