# Generated by Django 3.0.2 on 2020-02-06 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_auto_20200203_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('295a13a0-f0cd-4de5-86ee-8de0f0f2b172'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ef0602a1-5727-4f31-8c39-061f2dc1e474'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='historybuyer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2bef881f-28d3-4b00-becd-dfa200d11cf8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
