# Generated by Django 3.0.2 on 2020-02-02 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_uuid', models.UUIDField(default=uuid.UUID('dadfb30f-6b0b-4858-b867-34f33ce81952'), primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(blank=True, default='2ematsevmb', max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('amount', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('number_sold', models.IntegerField(default=0)),
                ('number_seen', models.IntegerField(default=0)),
                ('number_bought', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('picture_uuid', models.UUIDField(default=uuid.UUID('3ee969f9-01db-4fe6-9821-4474e3a797aa'), primary_key=True, serialize=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
