# Generated by Django 3.0.2 on 2020-02-02 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default='o7iu65qo07', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_uuid',
            field=models.UUIDField(default=uuid.UUID('bd726681-f6ac-4f0e-8074-a3b00de4cb3b'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='picture_uuid',
            field=models.UUIDField(default=uuid.UUID('b00c92c6-0574-448c-ae8f-cedb83d27227'), primary_key=True, serialize=False, unique=True),
        ),
    ]
