# Generated by Django 3.0.2 on 2020-02-02 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200202_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default='w6k1vpjgcs', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_uuid',
            field=models.UUIDField(default=uuid.UUID('bc0db8e8-2ae6-490b-90e1-705fb10290a0'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='picture_uuid',
            field=models.UUIDField(default=uuid.UUID('d0e4e2e9-706b-480a-9ccc-5353de5c1dc8'), primary_key=True, serialize=False, unique=True),
        ),
    ]
