# Generated by Django 3.0.2 on 2020-02-02 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200202_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default='xpugpuykfq', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_uuid',
            field=models.UUIDField(default=uuid.UUID('8154b11f-f7fc-453a-a5a7-eaa5fc908175'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='picture_uuid',
            field=models.UUIDField(default=uuid.UUID('a8a3c228-0936-414f-97f0-89b90c3e6a18'), primary_key=True, serialize=False, unique=True),
        ),
    ]
