# Generated by Django 3.0.2 on 2020-02-03 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200203_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_uuid',
        ),
        migrations.RemoveField(
            model_name='productpicture',
            name='picture_uuid',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06360b11-13e0-46e5-8d04-7664cc46a095'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='productpicture',
            name='id',
            field=models.UUIDField(default=uuid.UUID('83b65fc6-741c-48cd-958c-80088113a31b'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default='v0fojyo6al', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
