# Generated by Django 3.0.2 on 2020-02-03 09:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_auto_20200203_0938'),
        ('product', '0007_auto_20200203_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.Cart'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default='ocr1xdk0g3', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7cebd9ae-b7de-40f9-b019-8a769da218a2'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='id',
            field=models.UUIDField(default=uuid.UUID('375ea0f9-6f09-494f-8fed-4a4e8b2f2017'), primary_key=True, serialize=False, unique=True),
        ),
    ]
