# Generated by Django 3.0.2 on 2020-02-06 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200203_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default='jtncfleu6m', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2a281c11-c03c-46d3-b8ae-8d02ed21f5cd'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b7639c38-f1cd-4f71-bf8b-6fc843c5c87b'), primary_key=True, serialize=False, unique=True),
        ),
    ]
