# Generated by Django 3.0.2 on 2020-02-02 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='time_login',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='time_logout',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('d2aa294b-7f37-4ca8-805c-30b5f0aa5b38'), primary_key=True, serialize=False, unique=True),
        ),
    ]
