# Generated by Django 3.0.2 on 2020-02-02 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200202_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='time_login',
            new_name='login_at',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='time_logout',
            new_name='logout_at',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('e3a2f45d-c9ec-435c-bb49-5b684dc77c2a'), primary_key=True, serialize=False, unique=True),
        ),
    ]
