# Generated by Django 3.0.2 on 2020-02-03 05:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200202_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('0c61f065-868b-4c4a-8a60-33da86a6774f'), primary_key=True, serialize=False, unique=True),
        ),
    ]
