# Generated by Django 3.0.2 on 2020-02-03 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200203_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af61fa99-5bef-4fca-89cf-9c0723c5df66'), primary_key=True, serialize=False, unique=True),
        ),
    ]
