# Generated by Django 3.0.2 on 2020-02-06 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200203_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d9c6edc1-6647-4ab7-b382-b4e5b125a9e3'), primary_key=True, serialize=False, unique=True),
        ),
    ]
