# Generated by Django 3.0.6 on 2020-06-02 23:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('blacklisted_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['blacklisted_on'],
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('fea432e4-df1f-4775-a365-26938986b20e'), editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('password', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(max_length=255)),
                ('address_line1', models.TextField()),
                ('address_line2', models.TextField()),
                ('house_no', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('postal_code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_login', models.BooleanField(default=True)),
                ('time_login', models.DateTimeField()),
                ('time_logout', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoryBuyer',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6ed5e555-2866-4f9d-989c-bffbf4337747'), editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6cb9a3f4-2cc3-46d0-9eb4-566f75f00074'), primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
